# Generated by Django 4.1.7 on 2023-05-09 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('autor', models.CharField(max_length=150)),
                ('edicao', models.CharField(max_length=150)),
                ('conservacao', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('senha', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('ativa', models.BooleanField(default=True)),
                ('livro_solicitado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livro_solicitado', to='api.livro')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitante_do_livro', to='api.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='livro',
            name='dono_livro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dono_do_livro', to='api.usuario'),
        ),
        migrations.CreateModel(
            name='Doacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('ativa', models.BooleanField(default=True)),
                ('doador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doador_do_livro', to='api.usuario')),
                ('livro_doado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livro_doado', to='api.livro')),
            ],
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avaliacao_doador', models.DecimalField(decimal_places=2, max_digits=2)),
                ('avaliacao_solicitante', models.DecimalField(decimal_places=2, max_digits=2)),
                ('doador_avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doador', to='api.usuario')),
                ('solicitante_avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitante', to='api.usuario')),
            ],
        ),
    ]
